name: Unzip file
on: [push]
jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Unzip
        run: |
          unzip hikka-master.zip -d ./
          rm hikka-master.zip
      - name: Commit
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git commit -m "Auto unzip" || exit 0
          git push
